### ISSUE TITLE
模型下载链接有考虑更新吗

### ISSUE THREAD

**Issue by xanthichi** [AI-Hobbyist/Models#21]
模型索引中只有个别角色有下载链接，是否考虑将待更新的也附上链接

**Comment by JiangKaslana** [comment]
去b站上搜他在动态里面找。https://space.bilibili.com/6589795/dynamic

**Comment by xanthichi** [comment]
> 去b站上搜他在动态里面找。https://space.bilibili.com/6589795/dynamic

我知道那个大佬，但是我想要vits的模型啊（捂脸）

**Comment by JiangKaslana** [comment]
有的，你去那位大佬的alist里面看你就有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: youyi0218 ***@***.***&gt;
发送时间: 2024年2月10日 11:15
收件人: AI-Hobbyist/Models ***@***.***&gt;
抄送: Kiana Kaslanna ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [AI-Hobbyist/Models] 模型下载链接有考虑更新吗 (Issue #21)





  
去b站上搜他在动态里面找。https://space.bilibili.com/6589795/dynamic
  
我知道那个大佬，但是我想要vits的模型啊（捂脸）

**Comment by xanthichi** [comment]
> 有的，你去那位大佬的alist里面看你就有 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: youyi0218 ***@***.***&gt; 发送时间: 2024年2月10日 11:15 收件人: AI-Hobbyist/Models ***@***.***&gt; 抄送: Kiana Kaslanna ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [AI-Hobbyist/Models] 模型下载链接有考虑更新吗 (Issue #21) 去b站上搜他在动态里面找。https://space.bilibili.com/6589795/dynamic 我知道那个大佬，但是我想要vits的模型啊（捂脸） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

找到了，谢谢
